import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalErrorBoundary } from "@/widgets/error/GlobalErrorBoundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "시니어 건강증진 플랫폼",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex justify-center">
        <GlobalErrorBoundary>
          <div className="w-full md:w-2/3 px-4">{children}</div>
        </GlobalErrorBoundary>
      </body>
    </html>
  );
}
